version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
sphinx:
  configuration: docs/conf.py
# Optionally declare the Python requirements required to build your documentation
# python:
#   install:
#     - requirements: docs/requirements.txt
