name: Mac Unit Tests

on: [push]

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
#
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Pip Dependencies
      shell: bash
      run: |
        set -x
        pip install --upgrade pip
        pip install coveralls nose wxpython

    - name: Run Tests
      shell: bash
      run: xvfb-run python3 ${{ github.workspace }}/setup.py nosetests

    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls
