name: Release_to_PyPi

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Pip Dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Install setuptools also
      run: pip install setuptools

    - name: Build the Wheel
      shell: bash
      run: rm -rf dist/ build/ && python3 setup.py bdist_wheel sdist

    - name: Deploy on Test PyPi
      uses: pypa/gh-action-pypi-publish@37f50c210e3d2f9450da2cd423303d6a14a6e29f  # v1.5.1
      with:
        user: __token__
        password: ${{ secrets.PYPIPW }}
