name: Releases

on: [push]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-20.04]  # ubuntu-18.04
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Pip Dependencies
      shell: bash
      run: pip install pyinstaller pypubsub https://extras.wxpython.org/wxPython4/extras/linux/gtk2/ubuntu-18.04/wxPython-4.1.0-cp37-cp37m-linux_x86_64.whl

    - name: Build
      shell: bash
      run: |
        echo "VERSION=$(grep VERSION eplaunch/__init__.py | cut -d= -f2 | cut -d\" -f2)" >> $GITHUB_ENV
        echo "SHA=$(echo "${GITHUB_SHA}" | cut -c 1-8)" >> $GITHUB_ENV
        pyinstaller eplaunch.spec
        tar -C dist -zcf EPLaunch-"${VERSION}"-"${SHA}"-linux.tar.gz EPLaunch
        ls dist/
        ls dist/EPLaunch/
        mkdir tmp_build
        echo "Expecting to find file at: tmp_build/EPLaunch-${VERSION}-${SHA}-linux.tar.gz"
        cp EPLaunch-"${VERSION}"-"${SHA}"-linux.tar.gz tmp_build

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: EPLaunch-${{ matrix.os }}.tar.gz
        path: tmp_build/*.tar.gz


#    - name: Upload Release
#      uses: svenstaro/upload-release-action@v2
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: tmp_build/*.tar.gz
#        tag: ${{ github.ref }}
#        overwrite: true
#        file_glob: true

#pyinstaller wf_tester.spec
#tar -C dist -zcf EPLaunchWorkflowTester-"${VERSION}"-"${SHA}"-linux.tar.gz EpLaunchWorkflowTester
#cp EPLaunchWorkflowTester-"${VERSION}"-"${SHA}"-linux.tar.gz tmp_build
