name: Windows Unit Tests

on: [push]

jobs:
  unit_tests:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Pip Dependencies
      shell: bash
      run: pip install --user coveralls nose wxpython

    - name: Run headless test
      shell: bash
      run: python setup.py nosetests

    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls
