name: Windows Unit Tests

on: [push]

jobs:
  unit_tests:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Pip Dependencies
      shell: bash
      run: |
        set -x
        pip install --upgrade pip
        pip install coveralls nose wxpython

    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: python3 setup.py nosetests

    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls
